version: '3'

services:

  mysql-local:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=shortener
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"

  url-shortener-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: andela/url-shortener
    restart: on-failure
    depends_on:
      - mysql-local
    ports:
      - "8080:8080"
